name: artifact-cases
run-name: artifact-cases
on: [push]
jobs:
  test-artifact-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upload-two-files
        uses: actions/upload-artifact@v3
        with:
          name: more-files
          path: |
            ss.json
            report/cities.csv
            docs/docs.md
     # - name: download-two-files
     #   uses: actions/download-artifact@v3
     #   with:
     #     name: two-files
     #     path: ./two-files
     # - name: Display structure of downloaded files
     #   run: ls -lhR
     #   working-directory: ./two-files
