name: artifact-cases
run-name: artifact-cases
on: [push]
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first" > actual
      - uses: actions/upload-artifact@v3
        with:
          name: actual
          path: actual
  second:
    needs: [first]
    runs-on: ubuntu-latest
    steps:
      - run: echo "second" > actual2
      - uses: actions/upload-artifact@v3
        with:
          name: actual
          path: actual2
  verify:
      needs: [second]
      name: Verify contents
      runs-on: ubuntu-latest
      steps:
        - name: Fetch Integration Tests from Build
          uses: actions/download-artifact@v3
          with:
            name: actual
        - run: 
            ls -lh && cat actual && cat actual2