name: artifact-cases
run-name: artifact-cases
on: [push]
jobs:
  test-artifact-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upload-more-files
        uses: actions/upload-artifact@v3
        with:
          name: more-files
          path: |
            ss.json
            report/cities.csv
            docs/docs.md
      - name: download-more-files
        uses: actions/download-artifact@v3
        with:
          name: more-files
          path: ./more-files
      - name: Display structure of downloaded files
        run: ls -lR
        working-directory: ./
