on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make some test files
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
