on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make some test files
        run: |
          mkdir test
          echo "testing" > test/test_file1.md
          echo "testing" > test/test_file2.md

      - uses: actions/upload-artifact@v3
        with:
          name: test-files
          path: test/*
